//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HSMobile.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phone
    {
        public string PhonesID { get; set; }
        public string PicPhone { get; set; }
        public string PhonesName { get; set; }
        public string Chip { get; set; }
        public string Ram { get; set; }
        public string DL { get; set; }
        public string CameraSau { get; set; }
        public string CameraTruoc { get; set; }
        public string Pin { get; set; }
        public int OldPrice { get; set; }
        public byte Per { get; set; }
        public int NewPrice { get; set; }
        public string KindID { get; set; }
    
        public virtual KindOfPhone KindOfPhone { get; set; }
    }
}
